import React from "react";
import { BrowserRouter, Switch, Route } from "react-router-dom";
import useMediaQuery from "@material-ui/core/useMediaQuery";
import {
	unstable_createMuiStrictModeTheme as createMuiTheme,
	responsiveFontSizes,
	ThemeProvider,
} from "@material-ui/core/styles";

import CssBaseline from "@material-ui/core/CssBaseline";
import Paper from "@material-ui/core/Paper";
import Container from "@material-ui/core/Container";
import Grid from "@material-ui/core/Grid";
import Header from "./components/Header";
import Filters from "./components/Filters";
import Countries from "./components/Countries";

import useStyles from "./useStyles";
import { AppStore } from "./store";

const data = [
	{
		name: "Afghanistan",
		topLevelDomain: [".af"],
		alpha2Code: "AF",
		alpha3Code: "AFG",
		callingCodes: ["93"],
		capital: "Kabul",
		altSpellings: ["AF", "Afġānistān"],
		region: "Asia",
		subregion: "Southern Asia",
		population: 27657145,
		latlng: [33, 65],
		demonym: "Afghan",
		area: 652230,
		gini: 27.8,
		timezones: ["UTC+04:30"],
		borders: ["IRN", "PAK", "TKM", "UZB", "TJK", "CHN"],
		nativeName: "افغانستان",
		numericCode: "004",
		currencies: [{ code: "AFN", name: "Afghan afghani", symbol: "؋" }],
		languages: [
			{
				iso639_1: "ps",
				iso639_2: "pus",
				name: "Pashto",
				nativeName: "پښتو",
			},
			{
				iso639_1: "uz",
				iso639_2: "uzb",
				name: "Uzbek",
				nativeName: "Oʻzbek",
			},
			{
				iso639_1: "tk",
				iso639_2: "tuk",
				name: "Turkmen",
				nativeName: "Türkmen",
			},
		],
		translations: {
			de: "Afghanistan",
			es: "Afganistán",
			fr: "Afghanistan",
			ja: "アフガニスタン",
			it: "Afghanistan",
			br: "Afeganistão",
			pt: "Afeganistão",
			nl: "Afghanistan",
			hr: "Afganistan",
			fa: "افغانستان",
		},
		flag: "https://restcountries.eu/data/afg.svg",
		regionalBlocs: [
			{
				acronym: "SAARC",
				name: "South Asian Association for Regional Cooperation",
				otherAcronyms: [],
				otherNames: [],
			},
		],
		cioc: "AFG",
	},
	{
		name: "Åland Islands",
		topLevelDomain: [".ax"],
		alpha2Code: "AX",
		alpha3Code: "ALA",
		callingCodes: ["358"],
		capital: "Mariehamn",
		altSpellings: ["AX", "Aaland", "Aland", "Ahvenanmaa"],
		region: "Europe",
		subregion: "Northern Europe",
		population: 28875,
		latlng: [60.116667, 19.9],
		demonym: "Ålandish",
		area: 1580,
		gini: null,
		timezones: ["UTC+02:00"],
		borders: [],
		nativeName: "Åland",
		numericCode: "248",
		currencies: [{ code: "EUR", name: "Euro", symbol: "€" }],
		languages: [
			{
				iso639_1: "sv",
				iso639_2: "swe",
				name: "Swedish",
				nativeName: "svenska",
			},
		],
		translations: {
			de: "Åland",
			es: "Alandia",
			fr: "Åland",
			ja: "オーランド諸島",
			it: "Isole Aland",
			br: "Ilhas de Aland",
			pt: "Ilhas de Aland",
			nl: "Ålandeilanden",
			hr: "Ålandski otoci",
			fa: "جزایر الند",
		},
		flag: "https://restcountries.eu/data/ala.svg",
		regionalBlocs: [
			{
				acronym: "EU",
				name: "European Union",
				otherAcronyms: [],
				otherNames: [],
			},
		],
		cioc: "",
	},
	{
		name: "Australia",
		topLevelDomain: [".au"],
		alpha2Code: "AU",
		alpha3Code: "AUS",
		callingCodes: ["61"],
		capital: "Canberra",
		altSpellings: ["AU"],
		region: "Oceania",
		subregion: "Australia and New Zealand",
		population: 24117360,
		latlng: [-27, 133],
		demonym: "Australian",
		area: 7692024,
		gini: 30.5,
		timezones: [
			"UTC+05:00",
			"UTC+06:30",
			"UTC+07:00",
			"UTC+08:00",
			"UTC+09:30",
			"UTC+10:00",
			"UTC+10:30",
			"UTC+11:30",
		],
		borders: [],
		nativeName: "Australia",
		numericCode: "036",
		currencies: [{ code: "AUD", name: "Australian dollar", symbol: "$" }],
		languages: [
			{
				iso639_1: "en",
				iso639_2: "eng",
				name: "English",
				nativeName: "English",
			},
		],
		translations: {
			de: "Australien",
			es: "Australia",
			fr: "Australie",
			ja: "オーストラリア",
			it: "Australia",
			br: "Austrália",
			pt: "Austrália",
			nl: "Australië",
			hr: "Australija",
			fa: "استرالیا",
		},
		flag: "https://restcountries.eu/data/aus.svg",
		regionalBlocs: [],
		cioc: "AUS",
	},
	{
		name: "Benin",
		topLevelDomain: [".bj"],
		alpha2Code: "BJ",
		alpha3Code: "BEN",
		callingCodes: ["229"],
		capital: "Porto-Novo",
		altSpellings: ["BJ", "Republic of Benin", "République du Bénin"],
		region: "Africa",
		subregion: "Western Africa",
		population: 10653654,
		latlng: [9.5, 2.25],
		demonym: "Beninese",
		area: 112622,
		gini: 38.6,
		timezones: ["UTC+01:00"],
		borders: ["BFA", "NER", "NGA", "TGO"],
		nativeName: "Bénin",
		numericCode: "204",
		currencies: [
			{ code: "XOF", name: "West African CFA franc", symbol: "Fr" },
		],
		languages: [
			{
				iso639_1: "fr",
				iso639_2: "fra",
				name: "French",
				nativeName: "français",
			},
		],
		translations: {
			de: "Benin",
			es: "Benín",
			fr: "Bénin",
			ja: "ベナン",
			it: "Benin",
			br: "Benin",
			pt: "Benim",
			nl: "Benin",
			hr: "Benin",
			fa: "بنین",
		},
		flag: "https://restcountries.eu/data/ben.svg",
		regionalBlocs: [
			{
				acronym: "AU",
				name: "African Union",
				otherAcronyms: [],
				otherNames: [
					"الاتحاد الأفريقي",
					"Union africaine",
					"União Africana",
					"Unión Africana",
					"Umoja wa Afrika",
				],
			},
		],
		cioc: "BEN",
	},
	{
		name: "Bhutan",
		topLevelDomain: [".bt"],
		alpha2Code: "BT",
		alpha3Code: "BTN",
		callingCodes: ["975"],
		capital: "Thimphu",
		altSpellings: ["BT", "Kingdom of Bhutan"],
		region: "Asia",
		subregion: "Southern Asia",
		population: 775620,
		latlng: [27.5, 90.5],
		demonym: "Bhutanese",
		area: 38394,
		gini: 38.1,
		timezones: ["UTC+06:00"],
		borders: ["CHN", "IND"],
		nativeName: "ʼbrug-yul",
		numericCode: "064",
		currencies: [
			{ code: "BTN", name: "Bhutanese ngultrum", symbol: "Nu." },
			{ code: "INR", name: "Indian rupee", symbol: "₹" },
		],
		languages: [
			{
				iso639_1: "dz",
				iso639_2: "dzo",
				name: "Dzongkha",
				nativeName: "རྫོང་ཁ",
			},
		],
		translations: {
			de: "Bhutan",
			es: "Bután",
			fr: "Bhoutan",
			ja: "ブータン",
			it: "Bhutan",
			br: "Butão",
			pt: "Butão",
			nl: "Bhutan",
			hr: "Butan",
			fa: "بوتان",
		},
		flag: "https://restcountries.eu/data/btn.svg",
		regionalBlocs: [
			{
				acronym: "SAARC",
				name: "South Asian Association for Regional Cooperation",
				otherAcronyms: [],
				otherNames: [],
			},
		],
		cioc: "BHU",
	},
	{
		name: "Virgin Islands (U.S.)",
		topLevelDomain: [".vi"],
		alpha2Code: "VI",
		alpha3Code: "VIR",
		callingCodes: ["1 340"],
		capital: "Charlotte Amalie",
		altSpellings: [
			"VI",
			"USVI",
			"American Virgin Islands",
			"U.S. Virgin Islands",
		],
		region: "Americas",
		subregion: "Caribbean",
		population: 114743,
		latlng: [18.34, -64.93],
		demonym: "Virgin Islander",
		area: 346.36,
		gini: null,
		timezones: ["UTC-04:00"],
		borders: [],
		nativeName: "Virgin Islands of the United States",
		numericCode: "850",
		currencies: [
			{ code: "USD", name: "United States dollar", symbol: "$" },
		],
		languages: [
			{
				iso639_1: "en",
				iso639_2: "eng",
				name: "English",
				nativeName: "English",
			},
		],
		translations: {
			de: "Amerikanische Jungferninseln",
			es: "Islas Vírgenes de los Estados Unidos",
			fr: "Îles Vierges des États-Unis",
			ja: "アメリカ領ヴァージン諸島",
			it: "Isole Vergini americane",
			br: "Ilhas Virgens Americanas",
			pt: "Ilhas Virgens Americanas",
			nl: "Verenigde Staten Maagdeneilanden",
			hr: null,
			fa: "جزایر ویرجین آمریکا",
		},
		flag: "https://restcountries.eu/data/vir.svg",
		regionalBlocs: [],
		cioc: "ISV",
	},
	{
		name: "Cook Islands",
		topLevelDomain: [".ck"],
		alpha2Code: "CK",
		alpha3Code: "COK",
		callingCodes: ["682"],
		capital: "Avarua",
		altSpellings: ["CK", "Kūki 'Āirani"],
		region: "Oceania",
		subregion: "Polynesia",
		population: 18100,
		latlng: [-21.23333333, -159.76666666],
		demonym: "Cook Islander",
		area: 236,
		gini: null,
		timezones: ["UTC-10:00"],
		borders: [],
		nativeName: "Cook Islands",
		numericCode: "184",
		currencies: [
			{ code: "NZD", name: "New Zealand dollar", symbol: "$" },
			{ code: "CKD", name: "Cook Islands dollar", symbol: "$" },
		],
		languages: [
			{
				iso639_1: "en",
				iso639_2: "eng",
				name: "English",
				nativeName: "English",
			},
		],
		translations: {
			de: "Cookinseln",
			es: "Islas Cook",
			fr: "Îles Cook",
			ja: "クック諸島",
			it: "Isole Cook",
			br: "Ilhas Cook",
			pt: "Ilhas Cook",
			nl: "Cookeilanden",
			hr: "Cookovo Otočje",
			fa: "جزایر کوک",
		},
		flag: "https://restcountries.eu/data/cok.svg",
		regionalBlocs: [],
		cioc: "COK",
	},
	{
		name: "Finland",
		topLevelDomain: [".fi"],
		alpha2Code: "FI",
		alpha3Code: "FIN",
		callingCodes: ["358"],
		capital: "Helsinki",
		altSpellings: [
			"FI",
			"Suomi",
			"Republic of Finland",
			"Suomen tasavalta",
			"Republiken Finland",
		],
		region: "Europe",
		subregion: "Northern Europe",
		population: 5491817,
		latlng: [64, 26],
		demonym: "Finnish",
		area: 338424,
		gini: 26.9,
		timezones: ["UTC+02:00"],
		borders: ["NOR", "SWE", "RUS"],
		nativeName: "Suomi",
		numericCode: "246",
		currencies: [{ code: "EUR", name: "Euro", symbol: "€" }],
		languages: [
			{
				iso639_1: "fi",
				iso639_2: "fin",
				name: "Finnish",
				nativeName: "suomi",
			},
			{
				iso639_1: "sv",
				iso639_2: "swe",
				name: "Swedish",
				nativeName: "svenska",
			},
		],
		translations: {
			de: "Finnland",
			es: "Finlandia",
			fr: "Finlande",
			ja: "フィンランド",
			it: "Finlandia",
			br: "Finlândia",
			pt: "Finlândia",
			nl: "Finland",
			hr: "Finska",
			fa: "فنلاند",
		},
		flag: "https://restcountries.eu/data/fin.svg",
		regionalBlocs: [
			{
				acronym: "EU",
				name: "European Union",
				otherAcronyms: [],
				otherNames: [],
			},
		],
		cioc: "FIN",
	},
	{
		name: "Gabon",
		topLevelDomain: [".ga"],
		alpha2Code: "GA",
		alpha3Code: "GAB",
		callingCodes: ["241"],
		capital: "Libreville",
		altSpellings: ["GA", "Gabonese Republic", "République Gabonaise"],
		region: "Africa",
		subregion: "Middle Africa",
		population: 1802278,
		latlng: [-1, 11.75],
		demonym: "Gabonese",
		area: 267668,
		gini: 41.5,
		timezones: ["UTC+01:00"],
		borders: ["CMR", "COG", "GNQ"],
		nativeName: "Gabon",
		numericCode: "266",
		currencies: [
			{ code: "XAF", name: "Central African CFA franc", symbol: "Fr" },
		],
		languages: [
			{
				iso639_1: "fr",
				iso639_2: "fra",
				name: "French",
				nativeName: "français",
			},
		],
		translations: {
			de: "Gabun",
			es: "Gabón",
			fr: "Gabon",
			ja: "ガボン",
			it: "Gabon",
			br: "Gabão",
			pt: "Gabão",
			nl: "Gabon",
			hr: "Gabon",
			fa: "گابن",
		},
		flag: "https://restcountries.eu/data/gab.svg",
		regionalBlocs: [
			{
				acronym: "AU",
				name: "African Union",
				otherAcronyms: [],
				otherNames: [
					"الاتحاد الأفريقي",
					"Union africaine",
					"União Africana",
					"Unión Africana",
					"Umoja wa Afrika",
				],
			},
		],
		cioc: "GAB",
	},
	{
		name: "Guatemala",
		topLevelDomain: [".gt"],
		alpha2Code: "GT",
		alpha3Code: "GTM",
		callingCodes: ["502"],
		capital: "Guatemala City",
		altSpellings: ["GT"],
		region: "Americas",
		subregion: "Central America",
		population: 16176133,
		latlng: [15.5, -90.25],
		demonym: "Guatemalan",
		area: 108889,
		gini: 55.9,
		timezones: ["UTC-06:00"],
		borders: ["BLZ", "SLV", "HND", "MEX"],
		nativeName: "Guatemala",
		numericCode: "320",
		currencies: [{ code: "GTQ", name: "Guatemalan quetzal", symbol: "Q" }],
		languages: [
			{
				iso639_1: "es",
				iso639_2: "spa",
				name: "Spanish",
				nativeName: "Español",
			},
		],
		translations: {
			de: "Guatemala",
			es: "Guatemala",
			fr: "Guatemala",
			ja: "グアテマラ",
			it: "Guatemala",
			br: "Guatemala",
			pt: "Guatemala",
			nl: "Guatemala",
			hr: "Gvatemala",
			fa: "گواتمالا",
		},
		flag: "https://restcountries.eu/data/gtm.svg",
		regionalBlocs: [
			{
				acronym: "CAIS",
				name: "Central American Integration System",
				otherAcronyms: ["SICA"],
				otherNames: ["Sistema de la Integración Centroamericana,"],
			},
		],
		cioc: "GUA",
	},
	{
		name: "Indonesia",
		topLevelDomain: [".id"],
		alpha2Code: "ID",
		alpha3Code: "IDN",
		callingCodes: ["62"],
		capital: "Jakarta",
		altSpellings: ["ID", "Republic of Indonesia", "Republik Indonesia"],
		region: "Asia",
		subregion: "South-Eastern Asia",
		population: 258705000,
		latlng: [-5, 120],
		demonym: "Indonesian",
		area: 1904569,
		gini: 34,
		timezones: ["UTC+07:00", "UTC+08:00", "UTC+09:00"],
		borders: ["TLS", "MYS", "PNG"],
		nativeName: "Indonesia",
		numericCode: "360",
		currencies: [{ code: "IDR", name: "Indonesian rupiah", symbol: "Rp" }],
		languages: [
			{
				iso639_1: "id",
				iso639_2: "ind",
				name: "Indonesian",
				nativeName: "Bahasa Indonesia",
			},
		],
		translations: {
			de: "Indonesien",
			es: "Indonesia",
			fr: "Indonésie",
			ja: "インドネシア",
			it: "Indonesia",
			br: "Indonésia",
			pt: "Indonésia",
			nl: "Indonesië",
			hr: "Indonezija",
			fa: "اندونزی",
		},
		flag: "https://restcountries.eu/data/idn.svg",
		regionalBlocs: [
			{
				acronym: "ASEAN",
				name: "Association of Southeast Asian Nations",
				otherAcronyms: [],
				otherNames: [],
			},
		],
		cioc: "INA",
	},
	{
		name: "Kyrgyzstan",
		topLevelDomain: [".kg"],
		alpha2Code: "KG",
		alpha3Code: "KGZ",
		callingCodes: ["996"],
		capital: "Bishkek",
		altSpellings: [
			"KG",
			"Киргизия",
			"Kyrgyz Republic",
			"Кыргыз Республикасы",
			"Kyrgyz Respublikasy",
		],
		region: "Asia",
		subregion: "Central Asia",
		population: 6047800,
		latlng: [41, 75],
		demonym: "Kirghiz",
		area: 199951,
		gini: 36.2,
		timezones: ["UTC+06:00"],
		borders: ["CHN", "KAZ", "TJK", "UZB"],
		nativeName: "Кыргызстан",
		numericCode: "417",
		currencies: [{ code: "KGS", name: "Kyrgyzstani som", symbol: "с" }],
		languages: [
			{
				iso639_1: "ky",
				iso639_2: "kir",
				name: "Kyrgyz",
				nativeName: "Кыргызча",
			},
			{
				iso639_1: "ru",
				iso639_2: "rus",
				name: "Russian",
				nativeName: "Русский",
			},
		],
		translations: {
			de: "Kirgisistan",
			es: "Kirguizistán",
			fr: "Kirghizistan",
			ja: "キルギス",
			it: "Kirghizistan",
			br: "Quirguistão",
			pt: "Quirguizistão",
			nl: "Kirgizië",
			hr: "Kirgistan",
			fa: "قرقیزستان",
		},
		flag: "https://restcountries.eu/data/kgz.svg",
		regionalBlocs: [
			{
				acronym: "EEU",
				name: "Eurasian Economic Union",
				otherAcronyms: ["EAEU"],
				otherNames: [],
			},
		],
		cioc: "KGZ",
	},
	{
		name: "Macao",
		topLevelDomain: [".mo"],
		alpha2Code: "MO",
		alpha3Code: "MAC",
		callingCodes: ["853"],
		capital: "",
		altSpellings: [
			"MO",
			"澳门",
			"Macao Special Administrative Region of the People's Republic of China",
			"中華人民共和國澳門特別行政區",
			"Região Administrativa Especial de Macau da República Popular da China",
		],
		region: "Asia",
		subregion: "Eastern Asia",
		population: 649100,
		latlng: [22.16666666, 113.55],
		demonym: "Chinese",
		area: 30,
		gini: null,
		timezones: ["UTC+08:00"],
		borders: ["CHN"],
		nativeName: "澳門",
		numericCode: "446",
		currencies: [{ code: "MOP", name: "Macanese pataca", symbol: "P" }],
		languages: [
			{
				iso639_1: "zh",
				iso639_2: "zho",
				name: "Chinese",
				nativeName: "中文 (Zhōngwén)",
			},
			{
				iso639_1: "pt",
				iso639_2: "por",
				name: "Portuguese",
				nativeName: "Português",
			},
		],
		translations: {
			de: "Macao",
			es: "Macao",
			fr: "Macao",
			ja: "マカオ",
			it: "Macao",
			br: "Macau",
			pt: "Macau",
			nl: "Macao",
			hr: "Makao",
			fa: "مکائو",
		},
		flag: "https://restcountries.eu/data/mac.svg",
		regionalBlocs: [],
		cioc: "",
	},
	{
		name: "Moldova (Republic of)",
		topLevelDomain: [".md"],
		alpha2Code: "MD",
		alpha3Code: "MDA",
		callingCodes: ["373"],
		capital: "Chișinău",
		altSpellings: ["MD", "Republic of Moldova", "Republica Moldova"],
		region: "Europe",
		subregion: "Eastern Europe",
		population: 3553100,
		latlng: [47, 29],
		demonym: "Moldovan",
		area: 33846,
		gini: 33,
		timezones: ["UTC+02:00"],
		borders: ["ROU", "UKR"],
		nativeName: "Moldova",
		numericCode: "498",
		currencies: [{ code: "MDL", name: "Moldovan leu", symbol: "L" }],
		languages: [
			{
				iso639_1: "ro",
				iso639_2: "ron",
				name: "Romanian",
				nativeName: "Română",
			},
		],
		translations: {
			de: "Moldawie",
			es: "Moldavia",
			fr: "Moldavie",
			ja: "モルドバ共和国",
			it: "Moldavia",
			br: "Moldávia",
			pt: "Moldávia",
			nl: "Moldavië",
			hr: "Moldova",
			fa: "مولداوی",
		},
		flag: "https://restcountries.eu/data/mda.svg",
		regionalBlocs: [
			{
				acronym: "CEFTA",
				name: "Central European Free Trade Agreement",
				otherAcronyms: [],
				otherNames: [],
			},
		],
		cioc: "MDA",
	},
	{
		name: "Nigeria",
		topLevelDomain: [".ng"],
		alpha2Code: "NG",
		alpha3Code: "NGA",
		callingCodes: ["234"],
		capital: "Abuja",
		altSpellings: [
			"NG",
			"Nijeriya",
			"Naíjíríà",
			"Federal Republic of Nigeria",
		],
		region: "Africa",
		subregion: "Western Africa",
		population: 186988000,
		latlng: [10, 8],
		demonym: "Nigerian",
		area: 923768,
		gini: 48.8,
		timezones: ["UTC+01:00"],
		borders: ["BEN", "CMR", "TCD", "NER"],
		nativeName: "Nigeria",
		numericCode: "566",
		currencies: [{ code: "NGN", name: "Nigerian naira", symbol: "₦" }],
		languages: [
			{
				iso639_1: "en",
				iso639_2: "eng",
				name: "English",
				nativeName: "English",
			},
		],
		translations: {
			de: "Nigeria",
			es: "Nigeria",
			fr: "Nigéria",
			ja: "ナイジェリア",
			it: "Nigeria",
			br: "Nigéria",
			pt: "Nigéria",
			nl: "Nigeria",
			hr: "Nigerija",
			fa: "نیجریه",
		},
		flag: "https://restcountries.eu/data/nga.svg",
		regionalBlocs: [
			{
				acronym: "AU",
				name: "African Union",
				otherAcronyms: [],
				otherNames: [
					"الاتحاد الأفريقي",
					"Union africaine",
					"União Africana",
					"Unión Africana",
					"Umoja wa Afrika",
				],
			},
		],
		cioc: "NGR",
	},
	{
		name: "Poland",
		topLevelDomain: [".pl"],
		alpha2Code: "PL",
		alpha3Code: "POL",
		callingCodes: ["48"],
		capital: "Warsaw",
		altSpellings: ["PL", "Republic of Poland", "Rzeczpospolita Polska"],
		region: "Europe",
		subregion: "Eastern Europe",
		population: 38437239,
		latlng: [52, 20],
		demonym: "Polish",
		area: 312679,
		gini: 34.1,
		timezones: ["UTC+01:00"],
		borders: ["BLR", "CZE", "DEU", "LTU", "RUS", "SVK", "UKR"],
		nativeName: "Polska",
		numericCode: "616",
		currencies: [{ code: "PLN", name: "Polish złoty", symbol: "zł" }],
		languages: [
			{
				iso639_1: "pl",
				iso639_2: "pol",
				name: "Polish",
				nativeName: "język polski",
			},
		],
		translations: {
			de: "Polen",
			es: "Polonia",
			fr: "Pologne",
			ja: "ポーランド",
			it: "Polonia",
			br: "Polônia",
			pt: "Polónia",
			nl: "Polen",
			hr: "Poljska",
			fa: "لهستان",
		},
		flag: "https://restcountries.eu/data/pol.svg",
		regionalBlocs: [
			{
				acronym: "EU",
				name: "European Union",
				otherAcronyms: [],
				otherNames: [],
			},
		],
		cioc: "POL",
	},
	{
		name: "Sao Tome and Principe",
		topLevelDomain: [".st"],
		alpha2Code: "ST",
		alpha3Code: "STP",
		callingCodes: ["239"],
		capital: "São Tomé",
		altSpellings: [
			"ST",
			"Democratic Republic of São Tomé and Príncipe",
			"República Democrática de São Tomé e Príncipe",
		],
		region: "Africa",
		subregion: "Middle Africa",
		population: 187356,
		latlng: [1, 7],
		demonym: "Sao Tomean",
		area: 964,
		gini: 50.8,
		timezones: ["UTC"],
		borders: [],
		nativeName: "São Tomé e Príncipe",
		numericCode: "678",
		currencies: [
			{ code: "STD", name: "São Tomé and Príncipe dobra", symbol: "Db" },
		],
		languages: [
			{
				iso639_1: "pt",
				iso639_2: "por",
				name: "Portuguese",
				nativeName: "Português",
			},
		],
		translations: {
			de: "São Tomé und Príncipe",
			es: "Santo Tomé y Príncipe",
			fr: "Sao Tomé-et-Principe",
			ja: "サントメ・プリンシペ",
			it: "São Tomé e Príncipe",
			br: "São Tomé e Príncipe",
			pt: "São Tomé e Príncipe",
			nl: "Sao Tomé en Principe",
			hr: "Sveti Toma i Princip",
			fa: "کواترو دو فرویرو",
		},
		flag: "https://restcountries.eu/data/stp.svg",
		regionalBlocs: [
			{
				acronym: "AU",
				name: "African Union",
				otherAcronyms: [],
				otherNames: [
					"الاتحاد الأفريقي",
					"Union africaine",
					"União Africana",
					"Unión Africana",
					"Umoja wa Afrika",
				],
			},
		],
		cioc: "STP",
	},
	{
		name: "Sweden",
		topLevelDomain: [".se"],
		alpha2Code: "SE",
		alpha3Code: "SWE",
		callingCodes: ["46"],
		capital: "Stockholm",
		altSpellings: ["SE", "Kingdom of Sweden", "Konungariket Sverige"],
		region: "Europe",
		subregion: "Northern Europe",
		population: 9894888,
		latlng: [62, 15],
		demonym: "Swedish",
		area: 450295,
		gini: 25,
		timezones: ["UTC+01:00"],
		borders: ["FIN", "NOR"],
		nativeName: "Sverige",
		numericCode: "752",
		currencies: [{ code: "SEK", name: "Swedish krona", symbol: "kr" }],
		languages: [
			{
				iso639_1: "sv",
				iso639_2: "swe",
				name: "Swedish",
				nativeName: "svenska",
			},
		],
		translations: {
			de: "Schweden",
			es: "Suecia",
			fr: "Suède",
			ja: "スウェーデン",
			it: "Svezia",
			br: "Suécia",
			pt: "Suécia",
			nl: "Zweden",
			hr: "Švedska",
			fa: "سوئد",
		},
		flag: "https://restcountries.eu/data/swe.svg",
		regionalBlocs: [
			{
				acronym: "EU",
				name: "European Union",
				otherAcronyms: [],
				otherNames: [],
			},
		],
		cioc: "SWE",
	},
	{
		name: "United States of America",
		topLevelDomain: [".us"],
		alpha2Code: "US",
		alpha3Code: "USA",
		callingCodes: ["1"],
		capital: "Washington, D.C.",
		altSpellings: ["US", "USA", "United States of America"],
		region: "Americas",
		subregion: "Northern America",
		population: 323947000,
		latlng: [38, -97],
		demonym: "American",
		area: 9629091,
		gini: 48,
		timezones: [
			"UTC-12:00",
			"UTC-11:00",
			"UTC-10:00",
			"UTC-09:00",
			"UTC-08:00",
			"UTC-07:00",
			"UTC-06:00",
			"UTC-05:00",
			"UTC-04:00",
			"UTC+10:00",
			"UTC+12:00",
		],
		borders: ["CAN", "MEX"],
		nativeName: "United States",
		numericCode: "840",
		currencies: [
			{ code: "USD", name: "United States dollar", symbol: "$" },
		],
		languages: [
			{
				iso639_1: "en",
				iso639_2: "eng",
				name: "English",
				nativeName: "English",
			},
		],
		translations: {
			de: "Vereinigte Staaten von Amerika",
			es: "Estados Unidos",
			fr: "États-Unis",
			ja: "アメリカ合衆国",
			it: "Stati Uniti D'America",
			br: "Estados Unidos",
			pt: "Estados Unidos",
			nl: "Verenigde Staten",
			hr: "Sjedinjene Američke Države",
			fa: "ایالات متحده آمریکا",
		},
		flag: "https://restcountries.eu/data/usa.svg",
		regionalBlocs: [
			{
				acronym: "NAFTA",
				name: "North American Free Trade Agreement",
				otherAcronyms: [],
				otherNames: [
					"Tratado de Libre Comercio de América del Norte",
					"Accord de Libre-échange Nord-Américain",
				],
			},
		],
		cioc: "USA",
	},
	{
		name: "United Kingdom of Great Britain and Northern Ireland",
		topLevelDomain: [".uk"],
		alpha2Code: "GB",
		alpha3Code: "GBR",
		callingCodes: ["44"],
		capital: "London",
		altSpellings: ["GB", "UK", "Great Britain"],
		region: "Europe",
		subregion: "Northern Europe",
		population: 65110000,
		latlng: [54, -2],
		demonym: "British",
		area: 242900,
		gini: 34,
		timezones: [
			"UTC-08:00",
			"UTC-05:00",
			"UTC-04:00",
			"UTC-03:00",
			"UTC-02:00",
			"UTC",
			"UTC+01:00",
			"UTC+02:00",
			"UTC+06:00",
		],
		borders: ["IRL"],
		nativeName: "United Kingdom",
		numericCode: "826",
		currencies: [{ code: "GBP", name: "British pound", symbol: "£" }],
		languages: [
			{
				iso639_1: "en",
				iso639_2: "eng",
				name: "English",
				nativeName: "English",
			},
		],
		translations: {
			de: "Vereinigtes Königreich",
			es: "Reino Unido",
			fr: "Royaume-Uni",
			ja: "イギリス",
			it: "Regno Unito",
			br: "Reino Unido",
			pt: "Reino Unido",
			nl: "Verenigd Koninkrijk",
			hr: "Ujedinjeno Kraljevstvo",
			fa: "بریتانیای کبیر و ایرلند شمالی",
		},
		flag: "https://restcountries.eu/data/gbr.svg",
		regionalBlocs: [
			{
				acronym: "EU",
				name: "European Union",
				otherAcronyms: [],
				otherNames: [],
			},
		],
		cioc: "GBR",
	},
	{
		name: "Zimbabwe",
		topLevelDomain: [".zw"],
		alpha2Code: "ZW",
		alpha3Code: "ZWE",
		callingCodes: ["263"],
		capital: "Harare",
		altSpellings: ["ZW", "Republic of Zimbabwe"],
		region: "Africa",
		subregion: "Eastern Africa",
		population: 14240168,
		latlng: [-20, 30],
		demonym: "Zimbabwean",
		area: 390757,
		gini: null,
		timezones: ["UTC+02:00"],
		borders: ["BWA", "MOZ", "ZAF", "ZMB"],
		nativeName: "Zimbabwe",
		numericCode: "716",
		currencies: [
			{ code: "BWP", name: "Botswana pula", symbol: "P" },
			{ code: "GBP", name: "British pound", symbol: "£" },
			{ code: "CNY", name: "Chinese yuan", symbol: "¥" },
			{ code: "EUR", name: "Euro", symbol: "€" },
			{ code: "INR", name: "Indian rupee", symbol: "₹" },
			{ code: "JPY", name: "Japanese yen", symbol: "¥" },
			{ code: "ZAR", name: "South African rand", symbol: "Rs" },
			{ code: "USD", name: "United States dollar", symbol: "$" },
			{ code: "(none)", name: null, symbol: null },
		],
		languages: [
			{
				iso639_1: "en",
				iso639_2: "eng",
				name: "English",
				nativeName: "English",
			},
			{
				iso639_1: "sn",
				iso639_2: "sna",
				name: "Shona",
				nativeName: "chiShona",
			},
			{
				iso639_1: "nd",
				iso639_2: "nde",
				name: "Northern Ndebele",
				nativeName: "isiNdebele",
			},
		],
		translations: {
			de: "Simbabwe",
			es: "Zimbabue",
			fr: "Zimbabwe",
			ja: "ジンバブエ",
			it: "Zimbabwe",
			br: "Zimbabwe",
			pt: "Zimbabué",
			nl: "Zimbabwe",
			hr: "Zimbabve",
			fa: "زیمباوه",
		},
		flag: "https://restcountries.eu/data/zwe.svg",
		regionalBlocs: [
			{
				acronym: "AU",
				name: "African Union",
				otherAcronyms: [],
				otherNames: [
					"الاتحاد الأفريقي",
					"Union africaine",
					"União Africana",
					"Unión Africana",
					"Umoja wa Afrika",
				],
			},
		],
		cioc: "ZIM",
	},
];

const themeType = (dark: boolean) =>
	createMuiTheme({
		palette: {
			type: dark ? "dark" : "light",
		},
	});

function App() {
	const [dark, setDark] = React.useState(false);

	const { events } = React.useContext(AppStore);

	// Use system's dark or light mode settings
	const prefersDarkMode = useMediaQuery("(prefers-color-scheme: dark)");

	React.useEffect(() => setDark(prefersDarkMode), [prefersDarkMode]);

	React.useEffect(() => {
		// fetch("https://restcountries.eu/rest/v2/all")
		// 	.then(res => res.json())
		// 	.then(data => events.storeFetchedData(data))
		// 	.catch(err => console.log(new Error(err)));
		events.storeFetchedData(data);
	}, []);

	const theme = responsiveFontSizes(themeType(dark));

	const classes = useStyles();

	const changeTheme = () => setDark(!dark);

	return (
		<ThemeProvider theme={theme}>
			<BrowserRouter>
				<CssBaseline />
				<Paper elevation={0} square={true}>
					<Header event={changeTheme} dark={dark} />
					<Switch>
						<Route
							exact
							path='/'
							render={() => (
								<Container>
									<Grid
										container
										style={{ padding: "2rem 0" }}>
										<Grid
											item
											container
											xs={12}
											className={classes.gridSpacing}>
											<Filters />
										</Grid>
										<Grid
											item
											container
											xs={12}
											spacing={6}
											className={classes.gridSpacing}>
											<Countries />
										</Grid>
									</Grid>
								</Container>
							)}
						/>
						<Route path='/:name' render={() => <></>} />
					</Switch>
				</Paper>
			</BrowserRouter>
		</ThemeProvider>
	);
}

export default App;
